ALTER TABLE users
  ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'customer';

ALTER TABLE users
  ALTER COLUMN role SET DEFAULT 'customer';

ALTER TABLE vegetables
  ADD COLUMN IF NOT EXISTS image VARCHAR(1000);

UPDATE vegetables
SET image = COALESCE(image, '🥬')
WHERE image IS NULL;

ALTER TABLE vegetables
  ALTER COLUMN image SET NOT NULL;

ALTER TABLE vegetables
  ADD COLUMN IF NOT EXISTS listed BOOLEAN NOT NULL DEFAULT true;